export const LIVROS_BIBLIA = [
  { id: 'genesis', name: 'Gênesis', en: 'Genesis', chapters: 50 },
  { id: 'exodus', name: 'Êxodo', en: 'Exodus', chapters: 40 },
  { id: 'leviticus', name: 'Levítico', en: 'Leviticus', chapters: 27 },
  { id: 'numbers', name: 'Números', en: 'Numbers', chapters: 36 },
  { id: 'deuteronomy', name: 'Deuteronômio', en: 'Deuteronomy', chapters: 34 },
  { id: 'joshua', name: 'Josué', en: 'Joshua', chapters: 24 },
  { id: 'judges', name: 'Juízes', en: 'Judges', chapters: 21 },
  { id: 'ruth', name: 'Rute', en: 'Ruth', chapters: 4 },
  { id: '1samuel', name: '1 Samuel', en: '1 Samuel', chapters: 31 },
  { id: '2samuel', name: '2 Samuel', en: '2 Samuel', chapters: 24 },
  { id: '1kings', name: '1 Reis', en: '1 Kings', chapters: 22 },
  { id: '2kings', name: '2 Reis', en: '2 Kings', chapters: 25 },
  { id: '1chronicles', name: '1 Crônicas', en: '1 Chronicles', chapters: 29 },
  { id: '2chronicles', name: '2 Crônicas', en: '2 Chronicles', chapters: 36 },
  { id: 'ezra', name: 'Esdras', en: 'Ezra', chapters: 10 },
  { id: 'nehemiah', name: 'Neemias', en: 'Nehemiah', chapters: 13 },
  { id: 'esther', name: 'Ester', en: 'Esther', chapters: 10 },
  { id: 'job', name: 'Jó', en: 'Job', chapters: 42 },
  { id: 'psalms', name: 'Salmos', en: 'Psalms', chapters: 150 },
  { id: 'proverbs', name: 'Provérbios', en: 'Proverbs', chapters: 31 },
  { id: 'ecclesiastes', name: 'Eclesiastes', en: 'Ecclesiastes', chapters: 12 },
  { id: 'songofsolomon', name: 'Cânticos', en: 'Song of Solomon', chapters: 8 },
  { id: 'isaiah', name: 'Isaías', en: 'Isaiah', chapters: 66 },
  { id: 'jeremiah', name: 'Jeremias', en: 'Jeremiah', chapters: 52 },
  { id: 'lamentations', name: 'Lamentações', en: 'Lamentations', chapters: 5 },
  { id: 'ezekiel', name: 'Ezequiel', en: 'Ezekiel', chapters: 48 },
  { id: 'daniel', name: 'Daniel', en: 'Daniel', chapters: 12 },
  { id: 'hosea', name: 'Oséias', en: 'Hosea', chapters: 14 },
  { id: 'joel', name: 'Joel', en: 'Joel', chapters: 3 },
  { id: 'amos', name: 'Amós', en: 'Amos', chapters: 9 },
  { id: 'obadiah', name: 'Obadias', en: 'Obadiah', chapters: 1 },
  { id: 'jonah', name: 'Jonas', en: 'Jonah', chapters: 4 },
  { id: 'micah', name: 'Miquéias', en: 'Micah', chapters: 7 },
  { id: 'nahum', name: 'Naum', en: 'Nahum', chapters: 3 },
  { id: 'habakkuk', name: 'Habacuque', en: 'Habakkuk', chapters: 3 },
  { id: 'zephaniah', name: 'Sofonias', en: 'Zephaniah', chapters: 3 },
  { id: 'haggai', name: 'Ageu', en: 'Haggai', chapters: 2 },
  { id: 'zechariah', name: 'Zacarias', en: 'Zechariah', chapters: 14 },
  { id: 'malachi', name: 'Malaquias', en: 'Malachi', chapters: 4 },
  { id: 'matthew', name: 'Mateus', en: 'Matthew', chapters: 28 },
  { id: 'mark', name: 'Marcos', en: 'Mark', chapters: 16 },
  { id: 'luke', name: 'Lucas', en: 'Luke', chapters: 24 },
  { id: 'john', name: 'João', en: 'John', chapters: 21 },
  { id: 'acts', name: 'Atos', en: 'Acts', chapters: 28 },
  { id: 'romans', name: 'Romanos', en: 'Romans', chapters: 16 },
  { id: '1corinthians', name: '1 Coríntios', en: '1 Corinthians', chapters: 16 },
  { id: '2corinthians', name: '2 Coríntios', en: '2 Corinthians', chapters: 13 },
  { id: 'galatians', name: 'Gálatas', en: 'Galatians', chapters: 6 },
  { id: 'ephesians', name: 'Efésios', en: 'Ephesians', chapters: 6 },
  { id: 'philippians', name: 'Filipenses', en: 'Philippians', chapters: 4 },
  { id: 'colossians', name: 'Colossenses', en: 'Colossians', chapters: 4 },
  { id: '1thessalonians', name: '1 Tessalonicenses', en: '1 Thessalonians', chapters: 5 },
  { id: '2thessalonians', name: '2 Tessalonicenses', en: '2 Thessalonians', chapters: 3 },
  { id: '1timothy', name: '1 Timóteo', en: '1 Timothy', chapters: 6 },
  { id: '2timothy', name: '2 Timóteo', en: '2 Timothy', chapters: 4 },
  { id: 'titus', name: 'Tito', en: 'Titus', chapters: 3 },
  { id: 'philemon', name: 'Filemom', en: 'Philemon', chapters: 1 },
  { id: 'hebrews', name: 'Hebreus', en: 'Hebrews', chapters: 13 },
  { id: 'james', name: 'Tiago', en: 'James', chapters: 5 },
  { id: '1peter', name: '1 Pedro', en: '1 Peter', chapters: 5 },
  { id: '2peter', name: '2 Pedro', en: '2 Peter', chapters: 3 },
  { id: '1john', name: '1 João', en: '1 John', chapters: 5 },
  { id: '2john', name: '2 João', en: '2 John', chapters: 1 },
  { id: '3john', name: '3 João', en: '3 John', chapters: 1 },
  { id: 'jude', name: 'Judas', en: 'Jude', chapters: 1 },
  { id: 'revelation', name: 'Apocalipse', en: 'Revelation', chapters: 22 }
]
